#! /usr/bin/env perl

use warnings;
use strict;

use File::Copy;
use File::Basename;

################################################################################

sub exec_cmd {
    my $cmd = shift;
    chomp(my $res = `$cmd`);
    $res;
}

sub git_dir {
    chomp(my $dir = `git rev-parse --git-dir`);
    my $cmd = 'cd $(dirname "' . $dir . '"); pwd';
    my $parent = &exec_cmd('cd $(dirname "' . $dir . '"); pwd');
    my $name = &exec_cmd('basename "' . $dir . '"');
    "${parent}/$name";
}

sub list { &exec_cmd('cat "${GIT_HOOKS_HOME}/configs/hooks-list"'); }

sub enabled {
    join("\n", grep {not(($_ eq 'dispatcher') or /\.sample$/)} map {basename $_} glob(git_dir.'/hooks/*'));
}

sub prompt {
    my $prompt = shift;
    print $prompt;
    chomp(my $str = <STDIN>);
    $str;
}

sub usage {
    print <<'    EOL';
usage
synopsys
  git hooks list
  git hooks enabled
  git hooks disabled
  git hooks on [commands...]
  git hooks off [commands...]
  git hooks update [branch]
    EOL
}

################################################################################

unless (exists($ENV{GIT_HOOKS_HOME}) and -d $ENV{GIT_HOOKS_HOME}) {
    print('environment valiable GIT_HOOKS_HOME is not set', "\n");
    exit;
}

my $count = @ARGV;

if ($count == 0) {
    usage();
    exit 0;
}

my $cmd = shift;
my @args = @ARGV;
$count = @ARGV;

################################################################################

if ($cmd eq 'list') {
    print &list, "\n";
}
elsif ($cmd eq 'enabled') {
    print &enabled, "\n";
}
elsif ($cmd eq 'disabled') {
    my @list = split(/\r\n|\r|\n/, &list);
    my @enabled = split(/\r\n|\r|\n/, &enabled);

    my %count = ();
    foreach (@list, @enabled) { $count{$_}++; }
    my @diff = ();
    foreach (keys %count) {
        if ($count{$_} != 2) {
            push @diff, $_;
        }
    }
    foreach (sort @diff) {
        print $_, "\n";
    }
}
elsif ($cmd eq 'on') {
    if ($count == 0) {
        @args = split(/\r\n|\r|\n/, &list);
    }

    my $gitdir = &git_dir;
    my %conf = %{eval(&exec_cmd('cat "${GIT_HOOKS_HOME}/install-config"'))};
    my $githookshome = $conf{githookshome};
    my $usesymlink = $conf{usesymlink} eq 'true';
    if ($args[0] eq 'ci') {
        my $url = $count == 2 ? $args[1] : &prompt('job url:');
        `echo "#! /bin/sh\ncurl $url -so /dev/null" > "${gitdir}/hooks/ci"`;
        chmod(0755, "${gitdir}/hooks/ci");
    }
    else {
        foreach (@args) {
            if ($_ eq 'ci') { next; }

            if ($usesymlink) {
                `ln -s "${githookshome}/templates/common" "${gitdir}/hooks/$_"`;
            }
            else {
                copy "${githookshome}/templates/common", $gitdir . '/hooks/' . $_;
            }
        }
    }

    unless (-e "${gitdir}/hooks/dispatcher") {
        if ($usesymlink) {
            `ln -s "${githookshome}/templates/dispatcher" "${gitdir}/hooks/dispatcher"`;
        }
        else {
            copy "${githookshome}/templates/common", "${gitdir}/hooks/dispatcher";
        }
    }
}
elsif ($cmd eq 'off') {
    if ($count == 0) {
        @args = split(/\r\n|\r|\n/, &list);
    }

    my $gitdir = &git_dir;
    foreach (@args) {
        if ($_ eq 'dispatcher') { next; }

        `rm "${gitdir}/hooks/$_"` if (-e "${gitdir}/hooks/$_");
    }

    if (-e "${gitdir}/hooks/dispatcher") {
        `rm "${gitdir}/hooks/dispatcher"`;
    }
}
elsif ($cmd eq 'update') {
    if ($count == 0) {
        # TODO : デフォルト値は設定ファイルか何かに持たせたい
        $args[0] = 'origin/master';
    }

    my $home = &exec_cmd('echo ${GIT_HOOKS_HOME}');
    my $gitdir = $home . '/.git';
    chdir $home;
    &exec_cmd('git remote update');
    &exec_cmd('git reset --hard ' . $args[0]);

    my %conf = %{eval(&exec_cmd('cat "${GIT_HOOKS_HOME}/install-config"'))};
    my $usesymlink = $conf{usesymlink} eq 'true';
    my $gitcmddir = $conf{gitcmddir};
    my $templatedir = $conf{templatedir};
    if ($usesymlink) {
        # サブコマンドのコピー
        foreach my $i (`ls ${home}/commands/* 2>/dev/null`) {
            chomp(my $orig = $i);
            chomp(my $link = $gitcmddir . '/' . basename($i));
            `ln -s "$orig" "$link"` unless (-e $link);
        }

        # テンプレートのコピー
        copy "${home}/templates/dispatcher", "${templatedir}/dispatcher";
        chmod(0755, "${templatedir}/dispatcher");
        foreach my $h (`cat "${home}/configs/hooks-list"`) {
            chomp($h);
            unless ($h eq 'ci') {
                `ln -s "${home}/templates/common" "${templatedir}/$h` unless (-e "${templatedir}/$h");
            }
        }
    }
    else {
        # サブコマンドのコピー
        foreach my $i (`ls commands/* 2>/dev/null`) {
            chomp(my $src = $i);
            chomp(my $dst = $gitcmddir . '/' . basename($i));
            copy $src, $dst;
        }

        # テンプレートのコピー
        copy "${home}/templates/dispatcher", "${templatedir}/dispatcher";
        chmod(0755, "${templatedir}/dispatcher");
        foreach my $h (`cat "${home}/configs/hooks-list"`) {
            chomp($h);
            unless ($h eq 'ci') {
                copy "${home}/templates/common", "${templatedir}/$h";
            }
        }
    }
}
else {
    print "${cmd} is unknown command.\n";
    usage();
    exit 1;
}
