#! /bin/sh

hookdir=`cd $(dirname "$0"); pwd`
gitdir=`dirname "$hookdir"`

cmp "${hookdir}/hooks-list" "${GIT_HOOKS_HOME}/configs/hooks-list" >/dev/null
if [ $? = 1 ]; then
    # TODO : templateをアップデートする
fi

if [ `basename "$0"` = 'pre-receive' -a -x "${hookdir}/ci" ]; then
    "${hookdir}/ci"
fi

hook="${GIT_HOOKS_HOME}/hooks/$1"
shift

if [ -x "$hook" ]; then
    exec "$hook" "$gitdir" "$@"
fi
