#! /bin/sh

hookdir=`cd $(dirname "$0"); pwd`
gitdir=`dirname "$hookdir"`

if [ x"$GIT_HOOKS_HOME" = x"" ]; then
    echo "GIT_HOOKS_HOME is not set"
    exit 1
fi

cmp "${hookdir}/dispatcher" "${GIT_HOOKS_HOME}/templates/dispatcher" >/dev/null
if [ $? = 1 ]; then
    cp "${GIT_HOOKS_HOME}/templates/dispatcher" "${hookdir}/dispatcher.new"
fi

if [ `basename "$0"` = 'pre-receive' -a -x "${hookdir}/ci" ]; then
    "${hookdir}/ci"
fi

hook="${GIT_HOOKS_HOME}/hooks/$1"
shift

if [ -x "$hook" ]; then
    exec "$hook" "$gitdir" "$@"
fi
